#pragma config(Sensor, S2,     testColor,      sensorColorNxtGREEN)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
SensorType[testColor] = sensorColorNxtFULL;
sleep(2000);
SensorType[testColor] = sensorColorNxtBLUE;
}
